Traceback (most recent call last):
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/evanmuzzall/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load data
penguins = pd.read_csv("data/penguins.csv")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [19][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;66;03m# load data[39;00m
[0;32m----> 2[0m penguins [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_csv[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mdata/penguins.csv[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:610[0m, in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[1;32m    605[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[1;32m    606[0m     dialect, delimiter, delim_whitespace, engine, sep, defaults[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mdelimiter[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m,[39m[38;5;124m"[39m}
[1;32m    607[0m )
[1;32m    608[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[0;32m--> 610[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:462[0m, in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    459[0m _validate_names(kwds[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mnames[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m))
[1;32m    461[0m [38;5;66;03m# Create the parser.[39;00m
[0;32m--> 462[0m parser [38;5;241m=[39m [43mTextFileReader[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m    464[0m [38;5;28;01mif[39;00m chunksize [38;5;129;01mor[39;00m iterator:
[1;32m    465[0m     [38;5;28;01mreturn[39;00m parser

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:819[0m, in [0;36mTextFileReader.__init__[0;34m(self, f, engine, **kwds)[0m
[1;32m    816[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m [38;5;129;01min[39;00m kwds:
[1;32m    817[0m     [38;5;28mself[39m[38;5;241m.[39moptions[[38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m] [38;5;241m=[39m kwds[[38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m]
[0;32m--> 819[0m [38;5;28mself[39m[38;5;241m.[39m_engine [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_engine[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mengine[49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:1050[0m, in [0;36mTextFileReader._make_engine[0;34m(self, engine)[0m
[1;32m   1046[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1047[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mUnknown engine: [39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m (valid options are [39m[38;5;132;01m{[39;00mmapping[38;5;241m.[39mkeys()[38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m"[39m
[1;32m   1048[0m     )
[1;32m   1049[0m [38;5;66;03m# error: Too many arguments for "ParserBase"[39;00m
[0;32m-> 1050[0m [38;5;28;01mreturn[39;00m [43mmapping[49m[43m[[49m[43mengine[49m[43m][49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mf[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:1867[0m, in [0;36mCParserWrapper.__init__[0;34m(self, src, **kwds)[0m
[1;32m   1864[0m kwds[[38;5;124m"[39m[38;5;124musecols[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39musecols
[1;32m   1866[0m [38;5;66;03m# open handles[39;00m
[0;32m-> 1867[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open_handles[49m[43m([49m[43msrc[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m
[1;32m   1868[0m [38;5;28;01massert[39;00m [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m   1869[0m [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124mstorage_options[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mencoding[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmemory_map[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcompression[39m[38;5;124m"[39m):

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:1362[0m, in [0;36mParserBase._open_handles[0;34m(self, src, kwds)[0m
[1;32m   1358[0m [38;5;28;01mdef[39;00m [38;5;21m_open_handles[39m([38;5;28mself[39m, src: FilePathOrBuffer, kwds: Dict[[38;5;28mstr[39m, Any]) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m   1359[0m     [38;5;124;03m"""[39;00m
[1;32m   1360[0m [38;5;124;03m    Let the readers open IOHanldes after they are done with their potential raises.[39;00m
[1;32m   1361[0m [38;5;124;03m    """[39;00m
[0;32m-> 1362[0m     [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;241m=[39m [43mget_handle[49m[43m([49m
[1;32m   1363[0m [43m        [49m[43msrc[49m[43m,[49m
[1;32m   1364[0m [43m        [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m   1365[0m [43m        [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mencoding[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[1;32m   1366[0m [43m        [49m[43mcompression[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mcompression[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[1;32m   1367[0m [43m        [49m[43mmemory_map[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mmemory_map[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[43m,[49m
[1;32m   1368[0m [43m        [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mkwds[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mstorage_options[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[1;32m   1369[0m [43m    [49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/common.py:642[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    640[0m         errors [38;5;241m=[39m [38;5;124m"[39m[38;5;124mreplace[39m[38;5;124m"[39m
[1;32m    641[0m     [38;5;66;03m# Encoding[39;00m
[0;32m--> 642[0m     handle [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m
[1;32m    643[0m [43m        [49m[43mhandle[49m[43m,[49m
[1;32m    644[0m [43m        [49m[43mioargs[49m[38;5;241;43m.[39;49m[43mmode[49m[43m,[49m
[1;32m    645[0m [43m        [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mioargs[49m[38;5;241;43m.[39;49m[43mencoding[49m[43m,[49m
[1;32m    646[0m [43m        [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m,[49m
[1;32m    647[0m [43m        [49m[43mnewline[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m    648[0m [43m    [49m[43m)[49m
[1;32m    649[0m [38;5;28;01melse[39;00m:
[1;32m    650[0m     [38;5;66;03m# Binary mode[39;00m
[1;32m    651[0m     handle [38;5;241m=[39m [38;5;28mopen[39m(handle, ioargs[38;5;241m.[39mmode)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/penguins.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'data/penguins.csv'

